name: HunterVsRunner
version: '${project.version}'
main: nlerik.huntervsrunner.HunterVsRunner
api-version: '1.20'
commands:
  huntervsrunner:
    description: Open het menu
    usage: /huntervsrunner
  joinhunter:
    description: Join the hunter team
    usage: /joinhunter
  joinrunner:
    description: Join the runner team
    usage: /joinrunner
  startgame:
    description: Start the game
    usage: /startgame
  stopgame:
    description: Stop the game
    usage: /stopgame
